<tr class="racenet_row rankedmaps_click" <?= $this->match ? 'style="background-color: #302843;"' : '' ?>>
	<td style="font-size: 12px; text-align: right;">
        <?= $this->position ?>.
    </td>
	<td>			
		<a class="wmtt" rel="<?= $this->image ?>" href="/maps/details/id/<?= $this->id ?>/"><?= str_replace('+', 'plus', $this->name) ?></a>
		<!--span style="font-size: 10px;"><?= ($this->freestyle == "true" ? "freestyle" : "race") ?></span-->
	</td>
	<td>
		<?= $this->partial('rating-out.phtml', array("name" => str_replace('+', 'plus', $this->name), "rating" => $this->rating * 4, "disabled" => true, "info" => "($this->ratings rating". ($this->ratings != 1 ? 's' : '') .")")) ?>
	</td>
	<td style="width: 130px;">
        <? if(isset($this->items) && $this->items->count()): ?>
            <? foreach($this->items as $item): ?>
                <img width="16" src="/gfx/icons/<?= $item->item ?>_small.gif" alt="" />  
            <? endforeach; ?>
        <? else: ?>
            <span class="info">none</span>
        <? endif; ?>
    </td>
	<td style="text-align: left;">
		<?= $this->races ? $this->NumberFormat($this->races) : '<span class="info">none</span>' ?>
	</td>
	<td style="text-align: left;">
		<?= $this->playtime ? $this->Racetime($this->playtime) : '<span class="info">none</span>' ?>
	</td>
	<td style="text-align: right;">
		<?= (integer)$this->downloads ?>
		<? if( !empty( $this->file ) ): ?>		
		<a href="javascript:void(0);" onClick="download_map( <?= $this->id ?>, 'http://downloads.warsow-race.net/warsow/pk3s/racesow/<?= urlencode( $this->file ) ?>' );"><img align="absmiddle" src="/gfx/icons/ico_floppy.gif" border="0" /></a>
		<? else: ?>
		<img src="/gfx/icons/ico_nofile.gif" alt="x" title="Download is currently not available" />
		<? endif; ?>
	</td>
</tr>