<tr class="racenet_row rankedmaps_click" <?= $this->match ? 'style="background-color: #302843;"' : '' ?>>
	<td style="font-size: 14px; text-align: right;">
		<b><?= $this->position ? $this->position .'.' : '-' ?></b>&nbsp;&nbsp;
	</td>
	<td style="font-size: 14px;">           
        <a href="<?= $this->url(array("controller" => "player", "id" => $this->player_id), null, true) ?>/"><?= new Racenet_IngameColors($this->name) ?></a>
    </td>
	<td style="font-size: 14px; <?= $this->prejumped == 'true' ? 'color: red;' : 'color: green;' ?>">
        <?= $this->Racetime($this->time, Racenet_Filter_Racetime::FORMAT_INGAME, false) ?>
    </td>
	<td style="text-align: center; color: #fff; font-weight: bold;">
		<div style="margin-right: 5px;"><?= $this->NumberFormat($this->points) ?></div>		
	</td>
    <td style="font-size: 14px;">         
        <?= $this->NumberFormat($this->races) ?>
    </td>
    <td style="font-size: 14px;">         
        <?= $this->NumberFormat($this->tries) ?>
    </td>
    <td style="font-size: 14px;">         
        <?= $this->Racetime($this->duration)?>
    </td>
    <td style="font-size: 14px;">         
        <?= $this->playtime ? $this->Racetime($this->playtime) : "-" ?>
    </td>
    <td><span style="font-size: 10px;"><?= $this->created ?></span></td>
    <td><a style="font-size: 10px;" href="/server/<?= $this->serverIdent ?>"><?= new Racenet_IngameColors(str_replace('warsow-race.net', '', $this->servername)) ?></a></td>
	<td style="text-align: center;">
		<a href="javascript:void(0);" class="playermapraces_toggle" rel="<?= $this->player_id ?>,<?=$this->map_id ?>" title="">+</a>
	</td>
</tr>
<tr id="playermapraces_<?= $this->player_id ?>" style="display:none">
  <td colspan="11">
    <div class="inner"></div>
  </td>
</tr>
