<div style="margin-left: auto; margin-right: auto; width: 600px;">
    <div class="racenet_headrow">
       Map upload
    </div>
    
    <? if( isset( $this->message ) ): ?>
    <div class="racenet_row" style="color: <?= $this->messageColor ?>; font-weight: bold;">
       <?= $this->message ?>
    </div>
    <? endif; ?>
    
    <div class="racenet_row">
        <?= $this->form ?>
		<div rel="<?= $this->form->getUploadId() ?>" class="progressbar" style="display: none; margin-bottom: 10px; margin-top: 10px;">
			<div style="background-color: #fff; position: relative; border: 1px solid black; width: 350px; height: 20px; margin-left: auto; margin-right: auto; margin-bottom: 5px;">
	            <div class="bar" style="position: absolute; background-color: red; height: 100%; width: 0px;"></div>
            	<span class="progress" style="position: absolute; width: 100%; text-align: center;">0 %</span>
        	</div>
			<div style="position: relative; width: 350px; margin-left: auto; margin-right: auto;">
				<div style="float: left;" class="speed">0 kb/s</div>
				<div style="float: right;" class="time">caclulating time</div>
				<div style="clear: both;"></div>
			</div>
		</div>
    </div> 
    
    <span style="font-style: italic; font-size: 10px;">* mandatory field</span>
</div>