<div align="center" style="text-align: center;">
	<script type="text/javascript"><!--
		google_ad_client = "pub-5453957708279217"; google_alternate_ad_url = ""; google_ad_width = 468; google_ad_height = 60; google_ad_format = "468x60_as"; google_ad_type = "image"; google_ad_channel = "1845243861"; google_color_border = "3E3452"; google_color_bg = "3E3452"; google_color_link = "AECCEB"; google_color_text = "737ABC";google_color_url = "737ABC";
	//--></script>
	<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
	<div class="livespacer"></div>
</div>