<tr class="racenet_row">
	<td style="font-size: 14px; text-align: left;">
		<a href="<?= $this->url(array('controller' => 'groups', 'action' => 'details', 'id' => $this->id), null, true) ?>"><?= $this->name ?></a>
	</td>
	<td style="font-size: 14px; text-align: left;">
		<?= $this->tag ?>
	</td>
	<td style="font-size: 14px; text-align: left;">
		<?= $this->members ?>
	</td>
	<td style="font-size: 14px; text-align: left;">
		<?= $this->points ?>
	</td>
</tr>