<div style="margin-left: auto; margin-right: auto; width: 900px;">
    
    <table class="racenet" border="0" width="100%">
        <thead>
          <td colspan="9">
              <div style="float: left;">
				Invite player to group: <?= $this->clan->name ?>
              </div>
			  <div style="float: right">
				<a style="font-size: 14px;" href="<?= $this->url(array('action' => 'details')) ?>">back to group</a>
			  </div>
              <div style="clear: both;"></div>
          </td>
        </thead>
		<? if ($this->messages): ?>
		<tr><td colspan="9">
		<ul style="list-style: none; color: #0f0; font-weight: bold;">
		<? foreach ($this->messages as $message): ?>
			<li><?= $message ?></li>       
		<? endforeach ?>
		</ul></td></tr>
		<? endif; ?>
		<tr>
			<td colspan="9">
				<?= $this->form ?>
			</td>
		</tr>
    </table>
</div>
