<div style="width: 810px; margin-left: auto; margin-right: auto;">
	<div class="racenet_headrow">
		Finished races
	</div>
	<div class="racenet_row" style="margin-bottom: 15px;">
		<img src="/tools/graph_races.php" border="0" />
	</div>
	
	<div class="racenet_headrow">
		Started races
	</div>
	<div class="racenet_row" style="margin-bottom: 15px;">
		<img src="/tools/graph_races2.php" border="0" />
	</div>
	
	<div class="racenet_headrow">
		Active players
	</div>
	<div class="racenet_row" style="margin-bottom: 15px;">
		<img src="/tools/graph_players.php" border="0" />
	</div>
</div>