<? $this->stats = Serverstats::getInstance() ?>
<div style="width: 810px; margin-left: auto; margin-right: auto;">

    <a title="Racesow @ ModDB" href="http://www.moddb.com/mods/racesow" target="_blank"><img style="margin: 0 5px 10px 5px;" src="/gfx/banner/Racesow_Art_Banner.jpg" border="0" /></a>
	<div style="position: relative; top: -80px; width: 794px; color: #b40000; font-weight: bold; font-style: italic; text-align: right;">
		A competitive and skillful game<br/>
		The ultimate Warsow Race experience<br/>
		Race-mode and Freestyle-mode available<br/>
		100% realtime stats ingame and at warsow-race.net<br/>
	</div>
	
	<div style="position: relative; top: -30px;" class="fb-like" data-href="http://www.warsow-race.net" data-send="false" data-width="450" data-show-faces="false" data-colorscheme="dark" data-font="verdana"></div>
	<? $this->headMeta()->appendName('og:image', 'http://www.warsow-race.net/gfx/layout/logo.png'); ?>
	
    <div style="float: left; width: 50%;">
        <div class="racenet_headrow">Statistics overview</div>
        <br/>
        <table width="100%" cellspacing="0" cellpadding="0" class="players">
            <tr>
                <td class="label">Last stats reset:</td>
                <td class="content"><b><?= $this->stats->getLastReset() ?></b></td>
            </tr>
            <tr>
                <td class="label">Logged players:</td>
                <td class="content"><b><?= $this->stats->getNumPlayers() ?></b> <span class="info" style="float: none;">(ever)</span></td>
            </tr>
            <tr>
                <td class="label">Active players:</td>
                <td class="content"><b><?= $this->stats->getNumPlayers(false) ?></b></td>
            </tr>
            <tr>
                <td class="label">Registered users:</td>
                <td class="content"><b><?= $this->stats->getNumberOfUsers() ?></b></td>
            </tr>
            <tr>
                <td class="label">Linked nicknames:</td>
                <td class="content"><b><?= $this->stats->getNumberOfIngameLinkages() ?></b></td>
            </tr>
            <tr>
                <td class="label">Race maps:</td>
                <td class="content"><b><?= $this->stats->getNumMaps() ?></b></td>
            </tr>
            <tr>
                <td class="label">Freestyle maps:</td>
                <td class="content"><b><?= $this->stats->getNumMaps(true) ?></b></td>
            </tr>
            <tr>
                <td class="label">Downloaded maps:</td>
                <td class="content"><b><?= $this->stats->getNumberOfDownloads() ?></b> <span class="info" style="float: none;">(web)</span></td>
            </tr>
            <tr>
                <td class="label">Races today:</td>
                <td class="content"><b><?= $this->stats->getNumRacesToday() ?></b></td>
            </tr>
            <tr>
                <td class="label">Races yesterday:</td>
                <td class="content"><b><?= $this->stats->getNumRacesYesterday() ?></b></td>
            </tr>
            <tr>
                <td class="label">Started races:</td>
                <td class="content"><b><?= $this->stats->getNumTries() ?></b></td>
            </tr>
            <tr>
                <td class="label">Finished races:</td>
                <td class="content"><b><?= $this->stats->getNumRaces() ?></b></td>
            </tr>
            <tr>
                <td class="label">Time of finished races:</td>
                <td class="content"><b><?= $this->stats->getRaceTime() ?></b></td>
            </tr>			
            <tr>
                <td class="label">Pure racing time:</td>
                <td class="content"><b><?= $this->stats->getRacingTime() ?></b></td>
            </tr>
            <tr>
                <td class="label">Total Playtime:</td>
                <td class="content"><b><?= $this->stats->getPlayTime() ?></b></td>
            </tr>
        </table>
    </div>

    <div style="float: left; width: 5%;">&nbsp;</div>

    <div style="float: left; width: 45%">
        <div class="racenet_headrow" style="margin-bottom: 10px;">Racesow Quickstart</div>
        <div style="font-size: 20px; margin-bottom: 10px;">1. <a href="/forum/profile.php?mode=register&agreed=true">register a racenetID</a></div>
        <div style="font-size: 20px;">2. <a href="/settings/ingame">get your inGame Nickname</a></div>
        <br/>
        <b>Benefits of registration and ingame linkage:</b><br/>
        <ul style="padding: 0 0 0 20px;">
            <li style="margin-bottom: 10px;">
                play with any nickname but collect<br/>
                your stats under the linked one
            </li>
            <li style="margin-bottom: 10px;">
                protect your linked nickname from<br/>
                beeing used by other players
            </li>
            <li style="margin-bottom: 10px;">
                display your ingame nickname in<br/>
                the warsow-race.net communiy
            </li>
        </ul>
         
        <div class="racenet_headrow">Useful Downloads</div>
        <br/>
        <span style="font-size: 14px;"><a href="http://www.warsow.net/download/">Warsow 0.6 Download Page</a></span>
        <br/><br/>
        <span style="font-size: 14px;"><a href="http://www.warsow-race.net/forum/viewtopic.php?t=1155">Quake 3 Texture Replacement Pack</a></span>
        <br/><br/>
        <span style="font-size: 14px;"><a href="http://www.warsow-race.net/forum/viewtopic.php?t=1156">Warsow 0.21 Compatibility Texture Pack</a></span>
        <br/><br/>
        
        <div class="racenet_headrow">Racesow Links</div>
        <br/>
        <span style="font-size: 14px;"><a href="http://racesow.warsow-race.net">Project page</a></span>,
        <span style="font-size: 14px;"><a href="http://www.moddb.com/mods/racesow">ModDB</a></span>,
        <span style="font-size: 14px;"><a href="https://www.ohloh.net/p/racesow">Ohloh</a></span>,
        <span style="font-size: 14px;"><a href="http://www.comboutique.com/shop/homeboutique-4951.html?lang=EN" target="_blank">Race Clothing</a></span>
    </div>
        <br/><br/>
    </div>

    <div style="clear: both;"></div>
</div>