<div style="width: 810px; margin-left: auto; margin-right: auto;">
    <div class="racenet_headrow">
        Administration module
    </div>
    <div class="racenet_row">
		<ul>
			<li style="margin-bottom: 5px;"><a href="/admin/users">Admins</a></li>
			<li style="margin-bottom: 5px;"><a href="/admin/faq">FAQ</a></li>
			<li style="margin-bottom: 5px;"><a href="/admin/maps">Maps</a></li>
		</ul>
    </div>
</div>