</div>
                    </div>
                </div>
                <div style="position:relative; top:-32px; left: 5px;">
                    <span style="font-size: 9px;">This site is optimized for Mozilla Firefox 7.x</span>
                </div>
            </div>
        </div>
        
        <? /*
        <div align="center" style="margin-bottom: 20px;">
            <a target="_blank" href="http://www.warsownews.net/"><img border="0" src="http://www.warsownews.net/v1/Portals/_default/Skins/warsow5/warsownews-234.gif" alt="warsownews.net" /></a>
            <a target="_blank" href="http://www.warsow-arena.de/"><img border="0" src="http://www.warsow-arena.de/forum/images/banner/wsw_banner_6.png" alt="Warsow-Arena.de" title="Warsow-Arena.de" /></a>
            <a target="_blank" href="http://www.1337demos.com/"><img border="0" src="http://www.1337demos.com/images/banner/1337demos.com.jpg" alt="1337demos.com" /></a>
        </div>
        */ ?>
        
        <div id="statusbar">
            <div class="partners">
                <a target="_blank" href="http://www.1337demos.com"><img src="/gfx/banner/1337demos_80x15.gif" border="0" alt="1337deoms.com" /></a>
                <a target="_blank" href="http://www.warsow-arena.de"><img src="/gfx/banner/banner_warsowarena_80x15.gif" border="0" alt="warsow-arena.de" /></a>
                <!--a target="_blank" href="http://www.rankingcloud.de"><img src="/gfx/banner/rankingcloud.gif" border="0" alt="rankingcloud.de" /></a-->
            </div>
            
            <div class="imprint">
                <a href="/imprint/">imprint</a>
                &copy; 2006-<?= date('Y') ?> <a href="http://www.warsow-race.net/">warsow-race.net</a>
            </div>

            <div class="loader" id="main_loader">
                <img src="/gfx/ajax-loader.gif" alt="" border="0" title="loading..." />
            </div>            
        </div>
    </body>
</html>