<div>
	<? $this->rating = round($this->rating) ?>
	<input name="rating_<?= $this->name ?>" type="radio" class="rating" value="poor"<?= $this->rating == 1 ? ' checked="true"' : '' ?><?= $this->disabled ? ' disabled="true"' : '' ?>/>
	<input name="rating_<?= $this->name ?>" type="radio" class="rating" value="hmmm"<?= $this->rating == 2 ? ' checked="true"' : '' ?><?= $this->disabled ? ' disabled="true"' : '' ?>/>
	<input name="rating_<?= $this->name ?>" type="radio" class="rating" value="playable"<?= $this->rating == 3 ? ' checked="true"' : '' ?><?= $this->disabled ? ' disabled="true"' : '' ?>/>
	<input name="rating_<?= $this->name ?>" type="radio" class="rating" value="good"<?= $this->rating == 4 ? ' checked="true"' : '' ?><?= $this->disabled ? ' disabled="true"' : '' ?>/>
	<input name="rating_<?= $this->name ?>" type="radio" class="rating" value="awesome"<?= $this->rating == 5 ? ' checked="true"' : '' ?><?= $this->disabled ? ' disabled="true"' : '' ?>/>

	<span class="info"><?= $this->info ?></span>

	<div style="clear: left;"></div>
</div>