cp includes/admin_easymod.php.txt ../../../admin/admin_easymod.php
cp em_includes/em_functions.php ../../../admin/em_includes/em_functions.php
cp em_includes/em_cipher.php ../../../admin/em_includes/em_cipher.php
cp em_includes/em_schema.php ../../../admin/em_includes/em_schema.php
cp em_includes/em_modio.php ../../../admin/em_includes/em_modio.php
cp em_includes/em_ftp.php ../../../admin/em_includes/em_ftp.php
cp em_includes/index.htm ../../../admin/em_includes/index.htm
cp includes/sql/sql_builder.php ../../../includes/sql/sql_builder.php
cp includes/sql/sql_builder_mssql.php ../../../includes/sql/sql_builder_mssql.php
cp includes/sql/sql_builder_mysql.php ../../../includes/sql/sql_builder_mysql.php
cp includes/sql/sql_builder_postgresql.php ../../../includes/sql/sql_builder_postgresql.php
cp includes/sql/sql_parser.php ../../../includes/sql/sql_parser.php
cp includes/sql/sql_reserved_keywords.php ../../../includes/sql/sql_reserved_keywords.php
cp languages/lang_sql_parser.php ../../../language/lang_english/lang_sql_parser.php
cp languages/lang_easymod_english.php ../../../language/lang_english/lang_easymod.php
cp languages/lang_easymod_english.php ../../../language/lang_german/lang_easymod.php
cp languages/lang_easymod_english.php ../../../language/lang_german_formal/lang_easymod.php
cp includes/mod_complete.tpl ../../../templates/subSilver/admin/mod_complete.tpl
cp includes/mod_header.tpl ../../../templates/subSilver/admin/mod_header.tpl
cp includes/mod_history.tpl ../../../templates/subSilver/admin/mod_history.tpl
cp includes/mod_history_details.tpl ../../../templates/subSilver/admin/mod_history_details.tpl
cp includes/mod_install.tpl ../../../templates/subSilver/admin/mod_install.tpl
cp includes/mod_login.tpl ../../../templates/subSilver/admin/mod_login.tpl
cp includes/mod_process.tpl ../../../templates/subSilver/admin/mod_process.tpl
cp includes/mod_settings.tpl ../../../templates/subSilver/admin/mod_settings.tpl
cp includes/mod_sql_body.tpl ../../../templates/subSilver/admin/mod_sql_body.tpl
cp includes/mod_preview.tpl ../../../templates/subSilver/admin/mod_preview.tpl
cp includes/mod_diy_body.tpl ../../../templates/subSilver/admin/mod_diy_body.tpl
cp includes/mod_help.tpl ../../../templates/subSilver/admin/mod_help.tpl
cp easymod.gif ../../../templates/subSilver/images/easymod.gif
cp includes/emc.gif ../../../templates/subSilver/images/emc.gif
