<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Map extends BaseMap
{
    /**
     * Get the levelshot for the map
     *
     * @return string
     */
    public function getLevelshot()
    {
        $defaultSrc = '/gfx/levelshots/medium/nolevelshot.jpg';

        if (!isset($this->name)) {
            
            return $defaultSrc;
        }

        $levelshotPath = PATH_HTDOCS .'/gfx/levelshots/medium/'. strtolower($this->name) .'.jpg';
        $levelshotSrc = '/gfx/levelshots/medium/'. urlencode(strtolower($this->name)) .'.jpg';

        return (is_file($levelshotPath)) ? $levelshotSrc : $defaultSrc;
    }
    
    /**
     * Get the thumbnail image to be dispayed on mouseover
     *
     * @return string
     */
    public function getWmttImage()
    {
        $levelshotPath = PATH_HTDOCS .'/gfx/levelshots/thumbs/'. strtolower($this->name) .'.jpg';
        return '/gfx/levelshots/thumbs/'. ((is_file($levelshotPath)) ? strtolower($this->name) : 'nolevelshot') . '.jpg';
    }
    
    public function getHighscore()
    {
        $query = $this->_table->createQuery()
                ->from('PlayerMap')
                ->where('map_id = ?', $this->id)
                ->andwhere('time <> \'NULL\'')
                ->orderBy('time ASC')
                ->limit(1);
            
        if ($highscore = $query->fetchOne()) {
            
            return $highscore->time;
        }
        
        return null;
    }
}