<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhpbbSessions extends BasePhpbbSessions
{
    public function setUp()
    {
        $this->hasOne('PhpbbUsers as User', array(
            'local' => 'session_user_id',
            'foreign' => 'user_id',
        ));
    }
}